---
- name: A play to create EC2 resources and used to launch a CentOS 7 VM.
  hosts: localhost
  tasks:
    - name: create a VPC
      ec2_vpc_net:
        name: Ebrox_VPC
        cidr_block: "{{ vpc_cidr }}"
        region: "{{ aws_region }}"
        tenancy: default
      register: Ebrox_VPC

    - name: create a Public Subnet
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{ Ebrox_VPC.vpc.id }}"
        region: "{{ aws_region }}"
        cidr: "{{ PublicSubnet_cidr }}"
        tags:
          Name: Ebrox_Public_Subnet
      register: Ebrox_Public_Subnet

    - name: create a Private Subnet
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{ Ebrox_VPC.vpc.id }}"
        region: "{{ aws_region }}"
        cidr: "{{ PrivateSubnet_cidr }}"
        tags:
          Name: Ebrox_Private_Subnet
      register: Ebrox_Private_Subnet

    - name: create an Internet Gateway
      ec2_vpc_igw:
        vpc_id: "{{ Ebrox_VPC.vpc.id }}"
        region: "{{ aws_region }}"
        state: present
      register: Ebrox_IGW

    - name: Set up public route table
      ec2_vpc_route_table:
        vpc_id: "{{ Ebrox_VPC.vpc.id }}"
        region: "{{ aws_region }}"
        tags:
          Name: Ebrox_Public_Subnet_route_table
        subnets:
          - "{{ Ebrox_Public_Subnet.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ Ebrox_IGW.gateway_id }}"

    - name: Set up private route table
      ec2_vpc_route_table:
        vpc_id: "{{ Ebrox_VPC.vpc.id }}"
        region: "{{ aws_region }}"
        tags:
          Name: Ebrox_Private_Subnet_route_table
        subnets:
          - "{{ Ebrox_Private_Subnet.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ Ebrox_IGW.gateway_id }}"

    - name: Set up security group
      ec2_group:
        name: Ebrox_VPC_SG
        description: Ebrox security group
        vpc_id: "{{ Ebrox_VPC.vpc.id }}"
        region: "{{ aws_region }}"
        rules:
          - proto: tcp
            ports:
              - 80
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port 80

          - proto: tcp
            ports:
              - 22
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port 22

    - name: create ec2 instance using CentOS 7
      ec2_instance:
        name: Ebrox_EC2
        key_name: "{{ keypair_name }}"
        region: "{{ aws_region }}"
        vpc_subnet_id: "{{ Ebrox_Public_Subnet.subnet.id }}"
        instance_type: t2.micro
        security_group: "{{ securitygroup_name }}"
        network:
          assign_public_ip: true
        image_id: "{{ image }}"
